services:
  - type: web
    name: studypuff-live
    runtime: node
    region: frankfurt
    plan: starter
    rootDir: .
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: "20"
